{{- if .Values.imagePolicy.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedRegistries
metadata:
  name: flask-app-allowed-registries
spec:
  enforcementAction: {{ .Values.imagePolicy.enforcement }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
    {{- range .Values.imagePolicy.targetNamespaces }}
      - {{ . | quote }}
    {{- end }}
  parameters:
    registries:
    {{- range .Values.imagePolicy.allowedRegistries }}
      - {{ . | quote }}
    {{- end }}
{{- end }}