# .github/workflows/security-scans.yml
name: Security Scans

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  semgrep-scan:
    name: Semgrep SAST Scan
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run Semgrep scan
        run: |
          docker run -v $(pwd):/src \
            -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
            -e SEMGREP_REPO_URL=https://github.com/${{ github.repository }} \
            -e SEMGREP_REPO_NAME=${{ github.repository }} \
            -e SEMGREP_BRANCH=${{ github.ref_name }} \
            -e SEMGREP_JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -e SEMGREP_COMMIT=${{ github.sha }} \
            -e SEMGREP_PR_ID=${{ github.event.pull_request.number }} \
            semgrep/semgrep semgrep ci
      
      - name: Upload Semgrep SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: semgrep.sarif
          wait-for-processing: true

  gitleaks-scan:
    name: Gitleaks Secret Scanning
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run Gitleaks
        run: |
          docker run -v $(pwd):/path zricethezav/gitleaks:latest detect --source="/path" -v --report-format json --report-path gitleaks-report.json
        continue-on-error: true  # Prevent the workflow from failing if secrets are found
      
      - name: Check for Gitleaks output
        id: check-output
        run: |
          if [ -f gitleaks-report.json ]; then
            echo "Gitleaks found potential secrets. See the report for details."
            cat gitleaks-report.json | jq .
            echo "secrets_found=true" >> $GITHUB_OUTPUT
          else
            echo "No secrets found by Gitleaks."
            echo "secrets_found=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload Gitleaks report
        if: steps.check-output.outputs.secrets_found == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
