name: Security Scans
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep-scan:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Semgrep Scan
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          config: auto
          output: semgrep-results.json  # Specifiek het outputbestand
      
      - name: List files (Debug)
        run: find . -name "*.json" | grep -i semgrep
          
      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-results
          path: |
            .semgrep/semgrep-results.json
            .semgrep/*.json
            semgrep-results.json

  gitleaks-scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Gitleaks manually
        run: |
          # Download en installeer Gitleaks
          curl -sSfL https://github.com/zricethezav/gitleaks/releases/download/v8.16.3/gitleaks_8.16.3_linux_x64.tar.gz | tar -xz
          chmod +x gitleaks
          
          # Handmatig uitvoeren met output naar bestand
          ./gitleaks detect --source . --report-format json --report-path gitleaks-results.json || true
          
          # Controleer of het rapport bestaat, zo niet, maak een leeg rapport
          if [ ! -f gitleaks-results.json ]; then
            echo "[]" > gitleaks-results.json
            echo "Geen leaks gedetecteerd, empty rapport gemaakt"
          else
            echo "Gitleaks rapport succesvol gemaakt"
          fi
          
      - name: List files (Debug)
        run: ls -la
          
      - name: Upload Gitleaks results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-results
          path: gitleaks-results.json