

# name: Security Scans

# on:
#   push:
#     branches: [ main, master ]
#   # Scan on-demand through GitHub Actions interface:
#   workflow_dispatch: {}

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: ubuntu-latest
#     container:
#       # Docker image met Semgrep geïnstalleerd
#       image: semgrep/semgrep
#     steps:
#       - uses: actions/checkout@v4

#       # Voer semgrep scan één keer uit en sla resultaten op
#       - name: Run Semgrep Scan
#         run: |
#           # Maak directory voor resultaten
#           mkdir -p semgrep-results

#           # Voer scan uit met tee om zowel naar console als bestand te schrijven
#           semgrep --config=auto | tee semgrep-console-output.txt

#           # Sla resultaten op in verschillende formaten
#           semgrep --config=auto --output=semgrep-results/scan.json --json --quiet
#           semgrep --config=auto --output=semgrep-results/scan.sarif --sarif --quiet

#           # Voeg console output toe aan resultaten
#           mv semgrep-console-output.txt semgrep-results/

#       # Sla resultaten op als artifact
#       - name: Upload Scan Results
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: semgrep-results
#           path: semgrep-results/
#           retention-days: 7
#           if-no-files-found: warn

#   bandit_scan:
#     name: Bandit Security Scan
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Bandit (no fail)
#         run: |
#           pip install bandit

#           # Maak een output directory
#           mkdir -p bandit-results

#           # Voer scan uit met tee om zowel naar console als bestand te schrijven
#           bandit -ll -ii -r . | tee bandit-results/console-output.txt || echo "Bandit found issues - continuing anyway"

#           # Genereer JSON rapport (stil)
#           bandit -ll -ii -r . --ignore-nosec -f json -o bandit-results/report.json || echo "Bandit found issues - continuing anyway"

#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: bandit-results
#           path: bandit-results/
#           if-no-files-found: warn


# name: Security Scans

# on:
#   push:
#     branches: [ main, master ]
#   workflow_dispatch:

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: ubuntu-latest
#     container:
#       image: semgrep/semgrep
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Semgrep Scan
#         run: |
#           mkdir -p semgrep-results
#           semgrep --config=auto | tee semgrep-results/console-output.txt
#           semgrep --config=auto --output=semgrep-results/scan.json --json --quiet
#           semgrep --config=auto --output=semgrep-results/scan.sarif --sarif --quiet

#       - name: Upload Scan Results
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: semgrep-results
#           path: semgrep-results/
#           retention-days: 7
#           if-no-files-found: warn

#   bandit_scan:
#     name: Bandit Security Scan
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Bandit (no fail)
#         run: |
#           pip install bandit
#           mkdir -p bandit-results
#           bandit -ll -ii -r . | tee bandit-results/console-output.txt || echo "Bandit found issues - continuing anyway"
#           bandit -ll -ii -r . --ignore-nosec -f json -o bandit-results/report.json || echo "Bandit found issues - continuing anyway"

#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: bandit-results
#           path: bandit-results/
#           if-no-files-found: warn

#   gitleaks:
#     name: GitLeaks Secret Scan
#     runs-on: ubuntu-latest
#     env:
#       GITLEAKS_VERSION: v8.18.1
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Run GitLeaks with Docker
#         id: gitleaks_run
#         run: |
#           mkdir -p gitleaks-results
#           chmod 777 gitleaks-results  # Voeg volledige schrijfpermissies toe aan de map

#           docker run --rm --security-opt=no-new-privileges \
#           -v $(pwd):/path \
#           zricethezav/gitleaks:${GITLEAKS_VERSION} detect \
#           --source="/path" --verbose --report-format json --report-path=/path/gitleaks-results/report.json || true

#           # Toon resultaten in de logs
#           echo "## GitLeaks Findings"
#           if [ -f gitleaks-results/report.json ]; then
#             cat gitleaks-results/report.json
#             echo "scan_status=success" >> $GITHUB_OUTPUT
#             echo "## GitLeaks Findings" >> $GITHUB_STEP_SUMMARY
#             cat gitleaks-results/report.json >> $GITHUB_STEP_SUMMARY || echo "Failed to display GitLeaks findings"
#           else
#             echo "Warning: GitLeaks output file is missing"
#             echo "scan_status=incomplete" >> $GITHUB_OUTPUT
#           fi

#       - name: Upload GitLeaks Results
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: gitleaks-results
#           path: gitleaks-results/
#           retention-days: 7
#           if-no-files-found: warn
# name: Security Scans
# on:
#   push:
#     branches: [ main]
#   workflow_dispatch:
# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Semgrep Scan
#         run: |
#           # Maak resultaatdirectory
#           mkdir -p semgrep-results

#           # Gebruik Docker om Semgrep te draaien
#           docker run --rm -v "$(pwd):/src" returntocorp/semgrep semgrep --config=auto --output=/src/semgrep-results/scan.json --json /src

#           # Toon samenvatting in console
#           cat semgrep-results/scan.json | jq '.results[] | .extra.message' | sort | uniq -c || echo "Geen resultaten gevonden of fout bij verwerken output"

#       - name: Upload Scan Results
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: semgrep-results
#           path: semgrep-results/
#           retention-days: 7
#           if-no-files-found: warn

#   bandit_scan:
#     name: Bandit Security Scan
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Bandit (no fail)
#         run: |
#           # Maak resultaatdirectory
#           mkdir -p bandit-results

#           # Gebruik Docker om Bandit te draaien
#           docker run --rm -v "$(pwd):/src" python:3.11-slim bash -c "pip install bandit && cd /src && bandit -ll -ii -r . -f json -o /src/bandit-results/report.json || true"

#           # Toon samenvatting in console
#           cat bandit-results/report.json | jq '.results[] | .issue_text' | sort | uniq -c || echo "Geen resultaten gevonden of fout bij verwerken output"

#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: bandit-results
#           path: bandit-results/
#           if-no-files-found: warn

#   gitleaks:
#     name: GitLeaks Secret Scan
#     runs-on: self-hosted
#     env:
#       GITLEAKS_VERSION: v8.18.1
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Run GitLeaks
#         run: |
#           # Maak resultaatdirectory
#           mkdir -p gitleaks-results
#           chmod 777 gitleaks-results

#           # Gebruik Docker om GitLeaks te draaien
#           docker run --rm -v "$(pwd):/path" zricethezav/gitleaks:${GITLEAKS_VERSION} detect --source="/path" --report-format=json --report-path=/path/gitleaks-results/report.json || true

#           # Toon resultaten in console
#           if [ -f gitleaks-results/report.json ]; then
#             cat gitleaks-results/report.json | jq '.[] | .Description' | sort | uniq -c || echo "Geen resultaten of fout bij verwerken"
#           else
#             echo "Geen GitLeaks resultaatbestand gevonden"
#           fi

#       - name: Upload GitLeaks Results
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: gitleaks-results
#           path: gitleaks-results/
#           retention-days: 7
#           if-no-files-found: warn

#   upload_to_defectdojo:
#     name: Upload to DefectDojo
#     needs: [semgrep, bandit_scan, gitleaks]
#     runs-on: self-hosted
#     steps:
#       - name: Download all scan results
#         uses: actions/download-artifact@v4
#         with:
#           path: all-results

#       - name: Upload to DefectDojo
#         env:
#           DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
#           DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
#           DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
#         run: |
#           SCAN_DATE=$(date +%Y-%m-%d)

#           # Upload Semgrep resultaten
#           if [ -f all-results/semgrep-results/scan.json ]; then
#             echo "Uploading Semgrep results..."
#             curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
#               -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
#               -F "scan_date=${SCAN_DATE}" \
#               -F "scan_type=Semgrep JSON Report" \
#               -F "engagement=${DEFECTDOJO_ENGAGEMENT_ID}" \
#               -F "file=@all-results/semgrep-results/scan.json"
#           fi

#           # Upload Bandit resultaten
#           if [ -f all-results/bandit-results/report.json ]; then
#             echo "Uploading Bandit results..."
#             curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
#               -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
#               -F "scan_date=${SCAN_DATE}" \
#               -F "scan_type=Bandit Scan" \
#               -F "engagement=${DEFECTDOJO_ENGAGEMENT_ID}" \
#               -F "file=@all-results/bandit-results/report.json"
#           fi

#           # Upload GitLeaks resultaten
#           if [ -f all-results/gitleaks-results/report.json ]; then
#             echo "Uploading GitLeaks results..."
#             curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
#               -H "Authorization: Token ${DEFECTDOJO_API_KEY}" \
#               -F "scan_date=${SCAN_DATE}" \
#               -F "scan_type=Gitleaks Scan" \
#               -F "engagement=${DEFECTDOJO_ENGAGEMENT_ID}" \
#               -F "file=@all-results/gitleaks-results/report.json"
#           fi
# name: Security Scans
# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   semgrep:
#     name: Semgrep Scan
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Semgrep Scan (SARIF format)
#         run: |
#           mkdir -p semgrep-results
#           docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
#             semgrep --config=auto --output=/src/semgrep-results/scan.sarif --sarif /src
          
#           # Debug output
#           echo "=== SARIF Output Preview ==="
#           jq '.runs[0].results[0] | {message: .message.text, severity: .level}' semgrep-results/scan.sarif || echo "No results found"

#       - name: Upload Scan Results
#         uses: actions/upload-artifact@v4
#         with:
#           name: semgrep-results
#           path: semgrep-results/
#           retention-days: 7

#   bandit_scan:
#     name: Bandit Security Scan
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v4

#       - name: Run Bandit
#         run: |
#           mkdir -p bandit-results
#           docker run --rm -v "$(pwd):/src" python:3.11-slim bash -c \
#             "pip install bandit && cd /src && bandit -ll -ii -r . -f json -o /src/bandit-results/report.json || true"
          
#           echo "=== Bandit Results Summary ==="
#           jq '.results[] | .issue_text' bandit-results/report.json | sort | uniq -c || echo "No issues found"

#       - uses: actions/upload-artifact@v4
#         with:
#           name: bandit-results
#           path: bandit-results/

#   gitleaks:
#     name: GitLeaks Secret Scan
#     runs-on: self-hosted
#     env:
#       GITLEAKS_VERSION: v8.18.1
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Run GitLeaks
#         run: |
#           mkdir -p gitleaks-results
#           docker run --rm -v "$(pwd):/path" zricethezav/gitleaks:$GITLEAKS_VERSION \
#             detect --source="/path" --report-format=json --report-path=/path/gitleaks-results/report.json || true
          
#           echo "=== GitLeaks Findings ==="
#           jq '.[].Description' gitleaks-results/report.json | sort | uniq -c || echo "No secrets found"

#       - uses: actions/upload-artifact@v4
#         with:
#           name: gitleaks-results
#           path: gitleaks-results/

#   upload_to_defectdojo:
#     name: Upload to DefectDojo
#     needs: [semgrep, bandit_scan, gitleaks]
#     runs-on: self-hosted
#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           path: all-results

#       - name: Upload Results to DefectDojo
#         env:
#           DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
#           DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
#           DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
#         run: |
#           SCAN_DATE=$(date +%Y-%m-%d)

#           # Semgrep (SARIF)
#           if [ -f all-results/semgrep-results/scan.sarif ]; then
#             echo "Uploading Semgrep SARIF..."
#             curl -v -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
#               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
#               -F "scan_date=$SCAN_DATE" \
#               -F "scan_type=SARIF" \
#               -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
#               -F "file=@all-results/semgrep-results/scan.sarif"
#           fi

#           # Bandit
#           if [ -f all-results/bandit-results/report.json ]; then
#             echo "Uploading Bandit..."
#             curl -v -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
#               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
#               -F "scan_date=$SCAN_DATE" \
#               -F "scan_type=Bandit Scan" \
#               -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
#               -F "file=@all-results/bandit-results/report.json"
#           fi

#           # GitLeaks
#           if [ -f all-results/gitleaks-results/report.json ]; then
#             echo "Uploading GitLeaks..."
#             curl -v -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
#               -H "Authorization: Token $DEFECTDOJO_API_KEY" \
#               -F "scan_date=$SCAN_DATE" \
#               -F "scan_type=Gitleaks Scan" \
#               -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
#               -F "file=@all-results/gitleaks-results/report.json"
#           fi


name: Advanced Security Scans
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep (Full Security Scan)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run Deep Semgrep Scan
        run: |
          mkdir -p semgrep-results
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
            semgrep --config=p/security --config=p/ci \
                   --output=/src/semgrep-results/scan.sarif \
                   --sarif \
                   --metrics=off \
                   --severity=ERROR,WARNING,INFO \
                   /src
          
          echo "=== Top 10 Findings ==="
          jq -r '.runs[0].results[] | "\(.level): \(.message.text)"' semgrep-results/scan.sarif | head -n 10

      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results/

  bandit_scan:
    name: Bandit (Full Python Audit)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run Aggressive Bandit Scan
        run: |
          mkdir -p bandit-results
          docker run --rm -v "${{ github.workspace }}:/src" python:3.11-slim bash -c \
            "pip install bandit && cd /src && \
             bandit -lll -iii -r . -f json -o /src/bandit-results/report.json \
                   --ignore-nosec || true"
          
          echo "=== Critical Findings ==="
          jq -r '.results[] | select(.issue_severity == "HIGH") | .issue_text' bandit-results/report.json | sort | uniq -c

      - uses: actions/upload-artifact@v4
        with:
          name: bandit-results
          path: bandit-results/

  gitleaks:
    name: GitLeaks (Deep Secrets Scan)
    runs-on: self-hosted
    env:
      GITLEAKS_VERSION: v8.18.1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for secrets detection

      - name: Run Thorough GitLeaks Scan
        run: |
          mkdir -p gitleaks-results
          docker run --rm -v "${{ github.workspace }}:/path" zricethezav/gitleaks:$GITLEAKS_VERSION \
            detect --source="/path" \
                  --report-format=json \
                  --report-path=/path/gitleaks-results/report.json \
                  --verbose \
                  --redact \
                  --exit-code=0
          
          echo "=== Potential Secrets ==="
          jq -r '.[] | "\(.Description): \(.Secret)"' gitleaks-results/report.json | head -n 20

      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results
          path: gitleaks-results/

  upload_to_defectdojo:
    name: Upload to DefectDojo
    needs: [semgrep, bandit_scan, gitleaks]
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all-results

      - name: Validate Results
        run: |
          echo "=== Validating Scan Outputs ==="
          [ -f all-results/semgrep-results/scan.sarif ] && echo "Semgrep: OK" || echo "Semgrep: Missing"
          [ -f all-results/bandit-results/report.json ] && echo "Bandit: OK" || echo "Bandit: Missing"
          [ -f all-results/gitleaks-results/report.json ] && echo "GitLeaks: OK" || echo "GitLeaks: Missing"

      - name: Upload to DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          SCAN_DATE=$(date +%Y-%m-%d)
          
          # Enhanced error handling
          upload_scan() {
            local file=$1
            local scan_type=$2
            
            echo "⌛ Uploading $scan_type ($file)"
            curl -v -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DEFECTDOJO_API_KEY" \
              -F "scan_date=$SCAN_DATE" \
              -F "scan_type=$scan_type" \
              -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
              -F "file=@$file" \
              || echo "❌ Upload failed for $scan_type"
          }

          # Process all scans
          [ -f all-results/semgrep-results/scan.sarif ] && upload_scan all-results/semgrep-results/scan.sarif "SARIF"
          [ -f all-results/bandit-results/report.json ] && upload_scan all-results/bandit-results/report.json "Bandit Scan"
          [ -f all-results/gitleaks-results/report.json ] && upload_scan all-results/gitleaks-results/report.json "Gitleaks Scan"

          echo "✅ All uploads processed"