# name: Upload Semgrep to DefectDojo
# on:
#   workflow_run:
#     workflows: ["Modular SAST Workflow"]
#     types:
#       - completed

# jobs:
#   upload_semgrep:
#     name: Upload Semgrep to DefectDojo
#     runs-on: ubuntu-latest
#     steps:
#       # Download het Semgrep artifact
#       - name: Download Semgrep artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: semgrep-results
#           path: semgrep-results
#         continue-on-error: true

#       # Debug de inhoud
#       - name: List artifact contents
#         run: |
#           echo "=== Downloaded Artifacts ==="
#           ls -la
#           echo "=== Semgrep Results Directory ==="
#           ls -la semgrep-results || echo "No semgrep-results directory found"
#           find . -type f -name "*.json" | sort

#       # Upload naar DefectDojo
#       - name: Upload Semgrep to DefectDojo
#         if: hashFiles('semgrep-results/results.json') != ''
#         env:
#           DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
#           DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
#           DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
#         run: |
#           SCAN_DATE=$(date +%Y-%m-%d)
#           SEMGREP_FILE="semgrep-results/results.json"
          
#           echo "⌛ Uploading Semgrep scan from $SEMGREP_FILE"
          
#           # Toon bestandsgrootte en eerste regels
#           echo "File size: $(wc -c < $SEMGREP_FILE) bytes"
#           echo "First 10 lines:"
#           head -n 10 $SEMGREP_FILE
          
#           HTTP_CODE=$(curl -s -o response.txt -w "%{http_code}" \
#             -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
#             -H "Authorization: Token $DEFECTDOJO_API_KEY" \
#             -F "scan_date=$SCAN_DATE" \
#             -F "scan_type=Semgrep JSON Report" \
#             -F "close_old_findings=true" \
#             -F "deduplication_on_engagement=true" \
#             -F "engagement=$DEFECTDOJO_ENGAGEMENT_ID" \
#             -F "file=@$SEMGREP_FILE")
          
#           if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
#             echo "✅ Successfully uploaded Semgrep scan"
#             echo "Response:"
#             cat response.txt
#           else
#             echo "❌ Upload failed with HTTP code $HTTP_CODE"
#             echo "Error response:"
#             cat response.txt
#             exit 1
#           fi